name: users_dvp_app
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.8.1

dependencies:
  cherry_toast: ^1.13.0
  dart_mediatr: ^1.0.5
  equatable: ^2.0.7
  flex_color_scheme: ^8.3.0
  flutter:
    sdk: flutter
  flutter_bloc: ^9.1.1
  formz: ^0.8.0
  get_it: ^8.2.0
  go_router: ^16.3.0
  isar: ^3.1.0+1
  isar_flutter_libs: ^3.1.0+1
  lottie: ^3.3.2
  path_provider: ^2.1.5
  remixicon: ^1.4.1
  smooth_page_indicator: ^1.2.1

dev_dependencies:
  build_runner: ^2.4.11
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter
  isar_generator: ^3.1.0+1

flutter:
  uses-material-design: true

  assets:
    - assets/animations/
